FROM golang:1.24 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o binary.exe ./7_leader_via_etcd/cmd

FROM debian:12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/binary.exe /app/binary.exe
ENTRYPOINT ["/app/binary.exe"]
